CREATE TABLE IF NOT EXISTS orders (
    id SERIAL PRIMARY KEY,
    user_id INT NOT NULL,
    product VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    time_delivery INT NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    vendor_id INT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE orders ADD CONSTRAINT fk_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id);