version: '3'

services:
  postgres_db:
    container_name: sf_postgres_db
    image: postgres
    restart: always
    networks:
      - sf_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "6543:5432"
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  delivery_report_app:
    container_name: sf_delivery_report_app
    build: .
    restart: always
    networks:
      - sf_network
    environment:
      DB_HOST: postgres_db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
      DB_SSL_MODE: ${DB_SSL_MODE}
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db

networks:
  sf_network:
    driver: bridge
